# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111314)
$foreground = rgb(B3CACB)
$color0 = rgb(383B3C)
$color1 = rgb(041013)
$color2 = rgb(041013)
$color3 = rgb(041013)
$color4 = rgb(051417)
$color5 = rgb(163E40)
$color6 = rgb(1D4D50)
$color7 = rgb(8AABAC)
$color8 = rgb(617778)
$color9 = rgb(051519)
$color10 = rgb(051519)
$color11 = rgb(051519)
$color12 = rgb(071A1E)
$color13 = rgb(1E5356)
$color14 = rgb(26676A)
$color15 = rgb(8AABAC)
